### PR TITLE
Add additional sensors to the integration.

### PR DESCRIPTION
**Pull request by wonderslug**
This PR adds additional sensors to the Sutro Device Integration.

It adds the following sensors
* Bromine ppm
* Device Health

It also adds the following Binary Sensors
* Device Core Status
* Device Lid Open
* Device Online
* Device Taking Readings
* Hub Online

As well It adds the reading time to the device sensors that only get periodically read (chlorine, bromine, alkalinity, and ph)

Signed-off-by: Brian Towles <brian@towles.com>

### CODE REVIEW

**Review by ydogandjiev — APPROVED** [review]

**Comment by ydogandjiev** [comment]
@wonderslug, you can run the following command locally to fix the remaining issues:
```
 pre-commit run --all-files
```

**Comment by wonderslug** [comment]
yeah I was being lazy.

**Comment by ydogandjiev** [comment]
@wonderslug, is the change ready to merge?

**Comment by wonderslug** [comment]
Yeap good to go

**Comment by ydogandjiev** [comment]
@wonderslug, thank you for the contributions! I published your changes as part of the v0.0.3 release. All the new sensors you added appear to work well:
image

**Comment by wonderslug** [comment]
@ydogandjiev np glad to help.

**Pull request merged**
